fix android and ios build
When adding support for async send/recv apis in #87, ios and android builds got broken with following error

    error[E0433]: failed to resolve: use of undeclared crate or module `io`

Root cause:
Both ios and android platform code did not import std::io::self which caused it to fail.

Updated it to use full path to fix it